const express = require('express')
const path = require('path')
const DefinitionsService = require('./definitions-service')

const definitionsRouter = express.Router()
const jsonBodyParser = express.json()

// CREATE TABLE definition (
//   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//   user_id INTEGER REFERENCES we_user(id) ON DELETE CASCADE NOT NULL,
//   word_id INTEGER REFERENCES word(id) ON DELETE CASCADE NOT NULL,
//   text TEXT NOT NULL,
//   like_count INTEGER DEFAULT 0,
//   date_created TIMESTAMPTZ DEFAULT now() NOT NULL
// );

definitionsRouter.route('/').get((req, res, next) => {
  DefinitionsService.getAllDefinitions(req.app.get('db'))
    .then((defs) => {
      res.json(defs.map(DefinitionsService.serializeDefinition))
    })
    .catch(next)
})

module.exports = definitionsRouter
